[program:ops-metrics]
command=php /var/www/html/artisan ops:metrics:push
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/metrics.log

[program:ops-disk-metrics]
process_name=%(program_name)s
command=php /var/www/html/artisan ops:push-disk-metrics
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/ops-disk-metrics.log
stopwaitsecs=3600

[program:ops-network-push]
process_name=%(program_name)s
command=php /var/www/html/artisan ops:network:push
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/ops-network.log
stopwaitsecs=3600

[program:laravel-scheduler]
process_name=%(program_name)s_%(process_num)02d
; 这里要使用你具体的项目路径和 PHP 版本,例如 sail 环境可能需要 docker exec
command=php /var/www/html/artisan schedule:work --verbose --no-interaction
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/scheduler.log
stopwaitsecs=3600
