[program:ops-metrics]
command=php /var/www/html/artisan ops:metrics:push
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/metrics.log

[program:ops-disk-metrics]
process_name=%(program_name)s
command=php /var/www/html/artisan ops:push-disk-metrics
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/ops-disk-metrics.log
stopwaitsecs=3600

[program:ops-network-push]
process_name=%(program_name)s
command=php /var/www/html/artisan ops:network:push
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/ops-network.log
stopwaitsecs=3600

[program:docker-log-watcher]
process_name=%(program_name)s
command=php /var/www/html/artisan ops:docker-logs
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/ops-docker-logs.log
stopwaitsecs=3600
